I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 24, in script
    show image discord
  File "game/script.rpy", line 24, in <module>
    show image discord
NameError: name 'discord' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 24, in script
    show image discord
  File "/usr/share/renpy/renpy/ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/usr/share/renpy/renpy/ast.py", line 1364, in show_imspec
    expression = renpy.python.py_eval(expression)
  File "/usr/share/renpy/renpy/python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/usr/share/renpy/renpy/python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 24, in <module>
    show image discord
NameError: name 'discord' is not defined

Linux-6.2.0-63.fc38.x86_64-x86_64-with-glibc2.37 x86_64
Ren'Py 8.0.3.0
MadokaVN2 1.0
Fri Mar 10 14:12:35 2023
